source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'IOS_BaseProject_Example', :exclusive => true do
  pod "IOS_BaseProject", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "IOS_BaseProject", :path => "../"

  pod 'FBSnapshotTestCase'
end
